version: '3'
services:

  content-server:
    build: 
      context: ./content-server
      dockerfile: ./Dockerfile
    image: content-server
    ports:
    - "8081:8081"
    container_name: content-server 


  sorter:
    build: 
      context: ./sorter
      dockerfile: ./Dockerfile
    image: sorter
    volumes:
    - .:/data
    environment:
    - CONTENT_DIR=/data/medium_example
    depends_on:
    - content-server
    command:
    - ${CONTENT_DIR}


